package cn.tools.eterm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "veSWScnServiceSoap", targetNamespace = "urn:veSWScnService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface VeSWScnServiceSoap {

	/**
	 * 
	 * @param strUser
	 * @param bstrOffice
	 * @param bstrPnrNO
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "RtPnr")
	@WebResult(partName = "return")
	public String rtPnr(
			@WebParam(name = "bstrPnrNO", partName = "bstrPnrNO") String bstrPnrNO,
			@WebParam(name = "strUser", partName = "strUser") String strUser,
			@WebParam(name = "bstrOffice", partName = "bstrOffice") String bstrOffice);

	/**
	 * 
	 * @param bstrCmds
	 * @param strUser
	 * @param bstrOffice
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Book")
	@WebResult(partName = "return")
	public String book(
			@WebParam(name = "bstrCmds", partName = "bstrCmds") String bstrCmds,
			@WebParam(name = "strUser", partName = "strUser") String strUser,
			@WebParam(name = "bstrOffice", partName = "bstrOffice") String bstrOffice);

	/**
	 * 
	 * @param strUser
	 * @param bstrXCDH
	 * @param bstrOffice
	 * @param bstrTicketNO
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CreateXCD")
	@WebResult(partName = "return")
	public String createXCD(
			@WebParam(name = "bstrTicketNO", partName = "bstrTicketNO") String bstrTicketNO,
			@WebParam(name = "bstrXCDH", partName = "bstrXCDH") String bstrXCDH,
			@WebParam(name = "strUser", partName = "strUser") String strUser,
			@WebParam(name = "bstrOffice", partName = "bstrOffice") String bstrOffice);

	/**
	 * 
	 * @param strUser
	 * @param bstrXCDH
	 * @param bstrOffice
	 * @param bstrTicketNO
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CancelXCD")
	@WebResult(partName = "return")
	public String cancelXCD(
			@WebParam(name = "bstrTicketNO", partName = "bstrTicketNO") String bstrTicketNO,
			@WebParam(name = "bstrXCDH", partName = "bstrXCDH") String bstrXCDH,
			@WebParam(name = "strUser", partName = "strUser") String strUser,
			@WebParam(name = "bstrOffice", partName = "bstrOffice") String bstrOffice);

	/**
	 * 
	 * @param strUser
	 * @param bstrIFZD
	 * @param bstrHC
	 * @param bstrCFDate
	 * @param bstrHGKS
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AVH")
	@WebResult(partName = "return")
	public String avh(
			@WebParam(name = "bstrHC", partName = "bstrHC") String bstrHC,
			@WebParam(name = "bstrCFDate", partName = "bstrCFDate") String bstrCFDate,
			@WebParam(name = "bstrHGKS", partName = "bstrHGKS") String bstrHGKS,
			@WebParam(name = "bstrIFZD", partName = "bstrIFZD") String bstrIFZD,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param bstrDate
	 * @param strUser
	 * @param bstrHBH
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "FF")
	@WebResult(partName = "return")
	public String ff(
			@WebParam(name = "bstrHBH", partName = "bstrHBH") String bstrHBH,
			@WebParam(name = "bstrDate", partName = "bstrDate") String bstrDate,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param strUser
	 * @param bstrTicketNO
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Detr")
	@WebResult(partName = "return")
	public String detr(
			@WebParam(name = "bstrTicketNO", partName = "bstrTicketNO") String bstrTicketNO,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param strUser
	 * @param bstrPNR
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ParsePnr")
	@WebResult(partName = "return")
	public String parsePnr(
			@WebParam(name = "bstrPNR", partName = "bstrPNR") String bstrPNR,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param bstrUser
	 * @param bstrDYLX
	 * @param bstrIsTest
	 * @param bstrEI
	 * @param bstrOffice
	 * @param bstrPersons
	 * @param bstrSCNY
	 * @param bstrDDBH
	 * @param bstrPAT
	 * @param bstrPwd
	 * @param bstrPnrNO
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ETDZ")
	@WebResult(partName = "return")
	public String etdz(
			@WebParam(name = "bstrPnrNO", partName = "bstrPnrNO") String bstrPnrNO,
			@WebParam(name = "bstrUser", partName = "bstrUser") String bstrUser,
			@WebParam(name = "bstrPwd", partName = "bstrPwd") String bstrPwd,
			@WebParam(name = "bstrOffice", partName = "bstrOffice") String bstrOffice,
			@WebParam(name = "bstrEI", partName = "bstrEI") String bstrEI,
			@WebParam(name = "bstrPAT", partName = "bstrPAT") String bstrPAT,
			@WebParam(name = "bstrSCNY", partName = "bstrSCNY") String bstrSCNY,
			@WebParam(name = "bstrPersons", partName = "bstrPersons") String bstrPersons,
			@WebParam(name = "bstrDDBH", partName = "bstrDDBH") String bstrDDBH,
			@WebParam(name = "bstrDYLX", partName = "bstrDYLX") String bstrDYLX,
			@WebParam(name = "bstrIsTest", partName = "bstrIsTest") String bstrIsTest);

	/**
	 * 
	 * @param strOffice
	 * @param strUser
	 * @param bstrTicketNO
	 * @param strIsSuspended
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "TSS")
	@WebResult(partName = "return")
	public String tss(
			@WebParam(name = "bstrTicketNO", partName = "bstrTicketNO") String bstrTicketNO,
			@WebParam(name = "strUser", partName = "strUser") String strUser,
			@WebParam(name = "strIsSuspended", partName = "strIsSuspended") String strIsSuspended,
			@WebParam(name = "strOffice", partName = "strOffice") String strOffice);

	/**
	 * 
	 * @param bstrSS
	 * @param strUser
	 * @param bstrPAT
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "PAT")
	@WebResult(partName = "return")
	public String pat(
			@WebParam(name = "bstrSS", partName = "bstrSS") String bstrSS,
			@WebParam(name = "bstrPAT", partName = "bstrPAT") String bstrPAT,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param strUser
	 * @param bstrCityPair
	 * @param bstrCFDate
	 * @param bstrNeedParsed
	 * @param bstrHGKS
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "FD")
	@WebResult(partName = "return")
	public String fd(
			@WebParam(name = "bstrCityPair", partName = "bstrCityPair") String bstrCityPair,
			@WebParam(name = "bstrCFDate", partName = "bstrCFDate") String bstrCFDate,
			@WebParam(name = "bstrHGKS", partName = "bstrHGKS") String bstrHGKS,
			@WebParam(name = "bstrNeedParsed", partName = "bstrNeedParsed") String bstrNeedParsed,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param bstrTargetOffice
	 * @param strUser
	 * @param bstrPnrNO
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CY")
	@WebResult(partName = "return")
	public String cy(
			@WebParam(name = "bstrPnrNO", partName = "bstrPnrNO") String bstrPnrNO,
			@WebParam(name = "bstrTargetOffice", partName = "bstrTargetOffice") String bstrTargetOffice,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param bstrDate
	 * @param strUser
	 * @param bstrHBH
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "FLP")
	@WebResult(partName = "return")
	public String flp(
			@WebParam(name = "bstrHBH", partName = "bstrHBH") String bstrHBH,
			@WebParam(name = "bstrDate", partName = "bstrDate") String bstrDate,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param bstrDate
	 * @param strUser
	 * @param bstrCityPair
	 * @param bstrHGKS
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "NFD")
	@WebResult(partName = "return")
	public String nfd(
			@WebParam(name = "bstrCityPair", partName = "bstrCityPair") String bstrCityPair,
			@WebParam(name = "bstrDate", partName = "bstrDate") String bstrDate,
			@WebParam(name = "bstrHGKS", partName = "bstrHGKS") String bstrHGKS,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param bstrCmds
	 * @param strUser
	 * @param bstrNeedSealed
	 * @param bstrPnrNO
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "EditPNR")
	@WebResult(partName = "return")
	public String editPNR(
			@WebParam(name = "bstrPnrNO", partName = "bstrPnrNO") String bstrPnrNO,
			@WebParam(name = "bstrCmds", partName = "bstrCmds") String bstrCmds,
			@WebParam(name = "bstrNeedSealed", partName = "bstrNeedSealed") String bstrNeedSealed,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param strUser
	 * @param bstrPnrNO
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CancelPNR")
	@WebResult(partName = "return")
	public String cancelPNR(
			@WebParam(name = "bstrPnrNO", partName = "bstrPnrNO") String bstrPnrNO,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param strUser
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CLRF")
	@WebResult(partName = "return")
	public String clrf(
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param strUser
	 * @param strNewPassword
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AN")
	@WebResult(partName = "return")
	public String an(
			@WebParam(name = "strUser", partName = "strUser") String strUser,
			@WebParam(name = "strNewPassword", partName = "strNewPassword") String strNewPassword);

	/**
	 * 
	 * @param strUser
	 * @param strTickets
	 * @param strDate
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "TKScan")
	@WebResult(partName = "return")
	public String tkScan(
			@WebParam(name = "strUser", partName = "strUser") String strUser,
			@WebParam(name = "strDate", partName = "strDate") String strDate,
			@WebParam(name = "strTickets", partName = "strTickets") String strTickets);

	/**
	 * 
	 * @param strCode
	 * @param strPassword
	 * @param strUserName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AddUser")
	@WebResult(partName = "return")
	public String addUser(
			@WebParam(name = "strCode", partName = "strCode") String strCode,
			@WebParam(name = "strUserName", partName = "strUserName") String strUserName,
			@WebParam(name = "strPassword", partName = "strPassword") String strPassword);

	/**
	 * 
	 * @param strUser
	 * @param bstrIFZD
	 * @param bstrHC
	 * @param bstrCFDate
	 * @param bstrHGKS
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AVHXML")
	@WebResult(partName = "return")
	public String avhxml(
			@WebParam(name = "bstrHC", partName = "bstrHC") String bstrHC,
			@WebParam(name = "bstrCFDate", partName = "bstrCFDate") String bstrCFDate,
			@WebParam(name = "bstrHGKS", partName = "bstrHGKS") String bstrHGKS,
			@WebParam(name = "bstrIFZD", partName = "bstrIFZD") String bstrIFZD,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param strUser
	 * @param bstrDETR
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ONLYDETR")
	@WebResult(partName = "return")
	public String onlydetr(
			@WebParam(name = "bstrDETR", partName = "bstrDETR") String bstrDETR,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param strCode
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "DelUser")
	@WebResult(partName = "return")
	public String delUser(
			@WebParam(name = "strCode", partName = "strCode") String strCode);

	/**
	 * 
	 * @param strCode
	 * @param strPassword
	 * @param strUserName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "ModifyUser")
	@WebResult(partName = "return")
	public String modifyUser(
			@WebParam(name = "strCode", partName = "strCode") String strCode,
			@WebParam(name = "strUserName", partName = "strUserName") String strUserName,
			@WebParam(name = "strPassword", partName = "strPassword") String strPassword);

	/**
	 * 
	 * @param strUser
	 * @param bstrDETR
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "DetrXML")
	@WebResult(partName = "return")
	public String detrXML(
			@WebParam(name = "bstrDETR", partName = "bstrDETR") String bstrDETR,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param strUser
	 * @param bstrOffice
	 * @param bstrPAT
	 * @param bstrPnrNO
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "PNRPAT")
	@WebResult(partName = "return")
	public String pnrpat(
			@WebParam(name = "bstrPnrNO", partName = "bstrPnrNO") String bstrPnrNO,
			@WebParam(name = "bstrPAT", partName = "bstrPAT") String bstrPAT,
			@WebParam(name = "strUser", partName = "strUser") String strUser,
			@WebParam(name = "bstrOffice", partName = "bstrOffice") String bstrOffice);

	/**
	 * 
	 * @param bstrSS
	 * @param strUser
	 * @param bstrQTE
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QTE")
	@WebResult(partName = "return")
	public String qte(
			@WebParam(name = "bstrSS", partName = "bstrSS") String bstrSS,
			@WebParam(name = "bstrQTE", partName = "bstrQTE") String bstrQTE,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetAllGroups")
	@WebResult(partName = "return")
	public String getAllGroups();

	/**
	 * 
	 * @param strGroupID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetUsersByGroup")
	@WebResult(partName = "return")
	public String getUsersByGroup(
			@WebParam(name = "strGroupID", partName = "strGroupID") String strGroupID);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetAllGroupsAndUsers")
	@WebResult(partName = "return")
	public String getAllGroupsAndUsers();

	/**
	 * 
	 * @param strUserCode
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetGroupByUser")
	@WebResult(partName = "return")
	public String getGroupByUser(
			@WebParam(name = "strUserCode", partName = "strUserCode") String strUserCode);

	/**
	 * 
	 * @param strCode
	 * @param strGroupID
	 * @param strPassword
	 * @param strUserName
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AddUser2")
	@WebResult(partName = "return")
	public String addUser2(
			@WebParam(name = "strCode", partName = "strCode") String strCode,
			@WebParam(name = "strUserName", partName = "strUserName") String strUserName,
			@WebParam(name = "strPassword", partName = "strPassword") String strPassword,
			@WebParam(name = "strGroupID", partName = "strGroupID") String strGroupID);

	/**
	 * 
	 * @param strCode
	 * @param strNewGroupID
	 * @param strOldGroupID
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SwitchGroup")
	@WebResult(partName = "return")
	public String switchGroup(
			@WebParam(name = "strCode", partName = "strCode") String strCode,
			@WebParam(name = "strOldGroupID", partName = "strOldGroupID") String strOldGroupID,
			@WebParam(name = "strNewGroupID", partName = "strNewGroupID") String strNewGroupID);

	/**
	 * 
	 * @param strUser
	 * @param strCity
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "WF")
	@WebResult(partName = "return")
	public String wf(
			@WebParam(name = "strCity", partName = "strCity") String strCity,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param strUser
	 * @param bstrXCDH
	 * @param bstrOffice
	 * @param bstrTicketNO
	 * @param bstrTested
	 * @param bstrNeedParsed
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CreateXCD2")
	@WebResult(partName = "return")
	public String createXCD2(
			@WebParam(name = "bstrTicketNO", partName = "bstrTicketNO") String bstrTicketNO,
			@WebParam(name = "bstrXCDH", partName = "bstrXCDH") String bstrXCDH,
			@WebParam(name = "strUser", partName = "strUser") String strUser,
			@WebParam(name = "bstrOffice", partName = "bstrOffice") String bstrOffice,
			@WebParam(name = "bstrNeedParsed", partName = "bstrNeedParsed") String bstrNeedParsed,
			@WebParam(name = "bstrTested", partName = "bstrTested") String bstrTested);

	/**
	 * 
	 * @param bstrSS
	 * @param strUser
	 * @param bstrChildCmds
	 * @param bstrQTE
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "QTE2")
	@WebResult(partName = "return")
	public String qte2(
			@WebParam(name = "bstrSS", partName = "bstrSS") String bstrSS,
			@WebParam(name = "bstrQTE", partName = "bstrQTE") String bstrQTE,
			@WebParam(name = "bstrChildCmds", partName = "bstrChildCmds") String bstrChildCmds,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param strUser
	 * @param bstrTargetOffices
	 * @param bstrOfficesToDelete
	 * @param strPnrNO
	 * @param bstrOffice
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "PnrAuth")
	@WebResult(partName = "return")
	public String pnrAuth(
			@WebParam(name = "strPnrNO", partName = "strPnrNO") String strPnrNO,
			@WebParam(name = "bstrOffice", partName = "bstrOffice") String bstrOffice,
			@WebParam(name = "bstrTargetOffices", partName = "bstrTargetOffices") String bstrTargetOffices,
			@WebParam(name = "bstrOfficesToDelete", partName = "bstrOfficesToDelete") String bstrOfficesToDelete,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param strUser
	 * @param bstrName
	 * @param strPnrNO
	 * @param bstrOffice
	 * @param bstrNewFOID
	 * @param bstrOldFOID
	 * @param bstrType
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SSRFOID")
	@WebResult(partName = "return")
	public String ssrfoid(
			@WebParam(name = "strPnrNO", partName = "strPnrNO") String strPnrNO,
			@WebParam(name = "bstrName", partName = "bstrName") String bstrName,
			@WebParam(name = "bstrOldFOID", partName = "bstrOldFOID") String bstrOldFOID,
			@WebParam(name = "bstrNewFOID", partName = "bstrNewFOID") String bstrNewFOID,
			@WebParam(name = "bstrType", partName = "bstrType") String bstrType,
			@WebParam(name = "bstrOffice", partName = "bstrOffice") String bstrOffice,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param bstrDate
	 * @param strUser
	 * @param strFlightNO
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AVHFLT")
	@WebResult(partName = "return")
	public String avhflt(
			@WebParam(name = "strFlightNO", partName = "strFlightNO") String strFlightNO,
			@WebParam(name = "bstrDate", partName = "bstrDate") String bstrDate,
			@WebParam(name = "strUser", partName = "strUser") String strUser);

	/**
	 * 
	 * @param strUser
	 * @param bstrOffice
	 * @param bstrPAT
	 * @param bstrPnrNO
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "PNRPAT2")
	@WebResult(partName = "return")
	public String pnrpat2(
			@WebParam(name = "bstrPnrNO", partName = "bstrPnrNO") String bstrPnrNO,
			@WebParam(name = "bstrPAT", partName = "bstrPAT") String bstrPAT,
			@WebParam(name = "strUser", partName = "strUser") String strUser,
			@WebParam(name = "bstrOffice", partName = "bstrOffice") String bstrOffice);

	/**
	 * 
	 * @param strUser
	 * @param bstrOffice
	 * @param bstrTicketNO
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "XCDstate")
	@WebResult(partName = "return")
	public String xcDstate(
			@WebParam(name = "bstrTicketNO", partName = "bstrTicketNO") String bstrTicketNO,
			@WebParam(name = "strUser", partName = "strUser") String strUser,
			@WebParam(name = "bstrOffice", partName = "bstrOffice") String bstrOffice);

	/**
	 * 
	 * @param strUser
	 * @param bstrOffice
	 * @param bstrFlight
	 * @param bstrPnrNO
	 * @param strDate
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "RRTPNR")
	@WebResult(partName = "return")
	public String rrtpnr(
			@WebParam(name = "bstrPnrNO", partName = "bstrPnrNO") String bstrPnrNO,
			@WebParam(name = "bstrFlight", partName = "bstrFlight") String bstrFlight,
			@WebParam(name = "strDate", partName = "strDate") String strDate,
			@WebParam(name = "strUser", partName = "strUser") String strUser,
			@WebParam(name = "bstrOffice", partName = "bstrOffice") String bstrOffice);

	/**
	 * 
	 * @param bstrOffice
	 * @param bstrUserName
	 * @param bstrTicketNO
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "Detr2")
	@WebResult(partName = "return")
	public String detr2(
			@WebParam(name = "bstrTicketNO", partName = "bstrTicketNO") String bstrTicketNO,
			@WebParam(name = "bstrUserName", partName = "bstrUserName") String bstrUserName,
			@WebParam(name = "bstrOffice", partName = "bstrOffice") String bstrOffice);

	/**
	 * 
	 * @param strUser
	 * @param bstrOffice
	 * @param bstrPnrNO
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "RtxPnr")
	@WebResult(partName = "return")
	public String rtxPnr(
			@WebParam(name = "bstrPnrNO", partName = "bstrPnrNO") String bstrPnrNO,
			@WebParam(name = "strUser", partName = "strUser") String strUser,
			@WebParam(name = "bstrOffice", partName = "bstrOffice") String bstrOffice);

	/**
	 * 
	 * @param bstrInputXML
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GeneralCmdProcess")
	@WebResult(partName = "return")
	public String generalCmdProcess(
			@WebParam(name = "bstrInputXML", partName = "bstrInputXML") String bstrInputXML);

}
