package cn.myjava.jars.eterm;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * veSWScnService service = new veSWScnService();
 * VeSWScnServiceSoap portType = service.getVeSWScnServiceSoap();
 * portType.rtPnr(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "veSWScnService", targetNamespace = "urn:veSWScnService", wsdlLocation = "http://119.97.180.51:352/veSWScn/veSWScn.dll?Handler=GenveSWScnWSDL")
public class VeSWScnService extends Service {

	private final static URL VESWSCNSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(VeSWScnService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = VeSWScnService.class.getResource(".");
			url = new URL(baseUrl,
					"http://119.97.180.51:352/veSWScn/veSWScn.dll?Handler=GenveSWScnWSDL");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://119.97.180.51:352/veSWScn/veSWScn.dll?Handler=GenveSWScnWSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		VESWSCNSERVICE_WSDL_LOCATION = url;
	}

	public VeSWScnService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public VeSWScnService() {
		super(VESWSCNSERVICE_WSDL_LOCATION, new QName("urn:veSWScnService",
				"veSWScnService"));
	}

	/**
	 * 
	 * @return returns VeSWScnServiceSoap
	 */
	@WebEndpoint(name = "veSWScnServiceSoap")
	public VeSWScnServiceSoap getVeSWScnServiceSoap() {
		return super.getPort(new QName("urn:veSWScnService",
				"veSWScnServiceSoap"), VeSWScnServiceSoap.class);
	}

}
