package cn.myjava.jars.eterm;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * VeShareWebServiceService service = new VeShareWebServiceService();
 * VeShareWebServiceServiceSoap portType = service.getVeShareWebServiceServiceSoap();
 * portType.processRequest(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "VeShareWebServiceService", targetNamespace = "urn:VeShareWebServiceService", wsdlLocation = "http://119.97.180.51:352/VeShareWebService/VeShareWebService.dll?Handler=GenVeShareWebServiceWSDL")
public class VeShareWebServiceService extends Service {

	private final static URL VESHAREWEBSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(VeShareWebServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = VeShareWebServiceService.class
					.getResource(".");
			url = new URL(
					baseUrl,
					"http://119.97.180.51:352/VeShareWebService/VeShareWebService.dll?Handler=GenVeShareWebServiceWSDL");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://119.97.180.51:352/VeShareWebService/VeShareWebService.dll?Handler=GenVeShareWebServiceWSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		VESHAREWEBSERVICESERVICE_WSDL_LOCATION = url;
	}

	public VeShareWebServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public VeShareWebServiceService() {
		super(VESHAREWEBSERVICESERVICE_WSDL_LOCATION, new QName(
				"urn:VeShareWebServiceService", "VeShareWebServiceService"));
	}

	/**
	 * 
	 * @return returns VeShareWebServiceServiceSoap
	 */
	@WebEndpoint(name = "VeShareWebServiceServiceSoap")
	public VeShareWebServiceServiceSoap getVeShareWebServiceServiceSoap() {
		return super.getPort(new QName("urn:VeShareWebServiceService",
				"VeShareWebServiceServiceSoap"),
				VeShareWebServiceServiceSoap.class);
	}

}
